export * from './tag';

export {
  KIND_DEFAULT as TAG_KIND_DEFAULT,
  KIND_PRIMARY as TAG_KIND_PRIMARY,
  KIND_SECONDARY as TAG_KIND_SECONDARY,
  KIND_SUCCESS as TAG_KIND_SUCCESS,
  KIND_INFO as TAG_KIND_INFO,
  KIND_WARNING as TAG_KIND_WARNING,
  KIND_DANGER as TAG_KIND_DANGER,
  KINDS as TAG_KINDS,
  SIZE_SMALL as TAG_SIZE_SMALL,
  SIZE_MEDIUM as TAG_SIZE_MEDIUM,
  SIZE_LARGE as TAG_SIZE_LARGE,
  SIZES as TAG_SIZES,
} from './tag.constants';
