version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.9.0

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run:
          name: Install dependencies
          command: npm install && npm run lerna -- bootstrap

      - run:
          name: Build
          command: npm run lerna -- run build

