version: 2.1

executors:
  runner:
    docker:
      - image: circleci/node:9.11.2@sha256:edd46a503ae6228ef01b933384a9eb3562ba0d4ac58d4a89a73c497551e2a158
    working_directory: ~/repo

jobs:
  dependencies:
    executor: runner
    steps:
      - checkout
      - restore_cache:
          keys:
            - v0-deps-{{ .Branch }}
            - v0-deps-master
            - v0-deps-

      - run:
          name: Install dependencies
          command: npm install && npm run lerna -- bootstrap

      - save_cache:
          key: v0-deps-{{ .Branch }}
          paths:
            - "node_modules"
            - "packages/mixins-stylus/node_modules"
            - "packages/ui-stylus/node_modules"
            - "packages/ui/node_modules"
            - "packages/ui-react/node_modules"

      - persist_to_workspace:
          root: '.'
          paths:
            - '*'

  test:
    executor: runner
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Test
          command: npm run test

  build:
    executor: runner
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build
          command: npm run lerna -- run build

  deploy:
    executor: runner
    steps:
      - attach_workspace:
          at: ~/repo
      - add_ssh_keys:
          fingerprints:
            - "11:c8:1f:4c:fb:3b:92:2e:b6:d0:30:25:4e:73:b5:58"
      - run:
          name: Deploy pages
          command:
            npm run build-pages

workflows:
  version: 2.1

  build:
    jobs:
      - dependencies:
          filters:
            branches:
              ignore: gh-pages
      - test:
          requires:
            - dependencies
          filters:
            branches:
              ignore: gh-pages
      - build:
          requires:
            - dependencies
          filters:
            branches:
              ignore: gh-pages
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
