version: 2.1

executors:
  runner:
    docker:
      - image: circleci/node:13
    working_directory: ~/repo

jobs:
  dependencies:
    executor: runner
    steps:
      - checkout
      - restore_cache:
          keys:
            - v0-deps-{{ .Branch }}
            - v0-deps-master
            - v0-deps-

      - run:
          name: Install dependencies
          command: npm install && npm run lerna -- bootstrap

      - save_cache:
          key: v0-deps-{{ .Branch }}
          paths:
            - "node_modules"
            - "packages/mixins-stylus/node_modules"
            - "packages/ui-stylus/node_modules"
            - "packages/ui/node_modules"
            - "packages/ui-react/node_modules"

      - persist_to_workspace:
          root: '.'
          paths:
            - '*'

  test:
    executor: runner
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Test
          command: npm run test

  build:
    executor: runner
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build
          command: npm run build
      - persist_to_workspace:
          root: '.'
          paths:
            - '*'

  send-artifacts:
    executor: runner
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Send bundle stats to RelativeCI
          command: cd ./packages/ui-react && ./node_modules/.bin/relative-ci-agent

  build_pages:
    executor: runner
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Build
          command: npm run lerna -- run build-pages
      - persist_to_workspace:
          root: '.'
          paths:
            - '*'

  deploy:
    executor: runner
    steps:
      - attach_workspace:
          at: ~/repo
      - add_ssh_keys
      - run:
          name: Deploy pages
          command: |
            ./scripts/pre-deploy.sh
            npm run build-pages

  publish:
    executor: runner
    steps:
      - attach_workspace:
          at: ~/repo
      - add_ssh_keys
      - run: ./scripts/pre-deploy.sh
      - run: git reset --hard HEAD
      - deploy:
          command: npm run release

workflows:
  build:
    jobs:
      - dependencies:
          filters:
            branches:
              ignore: gh-pages
      - test:
          requires:
            - dependencies
          filters:
            branches:
              ignore: gh-pages
      - build:
          requires:
            - dependencies
          filters:
            branches:
              ignore: gh-pages
      - send-artifacts:
          requires:
            - build
          filters:
            branches:
              ignore: gh-pages

  publish-and-deploy:
    jobs:
      - dependencies:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - test:
          requires:
            - dependencies
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build:
          requires:
            - dependencies
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - publish:
          requires:
            - test
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
      - build_pages:
          requires:
            - test
            - build
          filters:
            tags:
              only: /^v\d*\.\d*\.\d*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - build_pages
          filters:
            tags:
              only: /^v\d*\.\d*\.\d*/
            branches:
              ignore: /.*/
