export * from './badge';

export {
  KIND_DEFAULT as BADGE_KIND_DEFAULT,
  KIND_PRIMARY as BADGE_KIND_PRIMARY,
  KIND_SECONDARY as BADGE_KIND_SECONDARY,
  KIND_SUCCESS as BADGE_KIND_SUCCESS,
  KIND_INFO as BADGE_KIND_INFO,
  KIND_WARNING as BADGE_KIND_WARNING,
  KIND_DANGER as BADGE_KIND_DANGER,
  KINDS as BADGE_KINDS,
  SIZE_SMALL as BADGE_SIZE_SMALL,
  SIZE_MEDIUM as BADGE_SIZE_MEDIUM,
  SIZE_LARGE as BADGE_SIZE_LARGE,
  SIZES as BADGE_SIZES
} from './badge.constants';
